version: '3'

services:
    backend:
      build: docker/php/8.1     
      container_name: backend_${projectName}
      tty: true
      ports:
        - 80:80
      volumes:
        - ./backend:/var/www/html/
      networks:
        - backend
      hostname: localhost

networks:
  backend:
    