FROM php:8.1-rc-apache-buster

RUN apt-get update

RUN apt-get update -y && apt-get install -y curl 

#mysqli
#RUN apt-get install zlib1g-dev 

#RUN yes "" | pecl install pecl_http --with-http-zlib-dir=/usr


